### ISSUE TITLE
Fonts loading on scroll doesn't works in grid view

### ISSUE THREAD

**Issue by jardicc** [thomaspark/fontcdn#4]
FullHD, chrome
Doesn't works becouse scrollbar can't move.
http://sklad.bereza.cz/00-jarda/00_screenshot/2015-08-07_232650.jpg

**Comment by albertorestifo** [comment]
Getting the same issue, I have a 27inch display, and there is no scrolling, so the next set of fonts is never loaded.

Simple fix: add a load more button

**Comment by thomaspark** [comment]
That's what you get for having a bigger display than me. :stuck_out_tongue: 

Having trouble getting this working properly with react-infinite or this workaround: https://github.com/seatgeek/react-infinite/issues/39

So in the meantime, I'm setting batch size to force scroll. Let me know if this gets fonts loading for you.

**Comment by albertorestifo** [comment]
Working fine for me

**Comment by jardicc** [comment]
Now it works fine
